name: Deploy Azure Functions API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: parkering-api-1759835139
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'
  SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Resolve Project Dependencies Using Npm'
      run: |
        npm ci || npm install
        npm run build

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      run: |
        # Pakk prosjektet
        zip -r functionapp.zip . -x "node_modules/*" ".git/*" "*.zip" ".github/*"
        
        # Deploy via Azure CLI
        az functionapp deployment source config-zip \
          --resource-group parkering-rg \
          --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
          --src functionapp.zip
