name: Deploy Azure Functions API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#env:
#  AZURE_FUNCTIONAPP_NAME: parkering-api-1759689187
#  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
#  NODE_VERSION: '20.x'

env:
  AZURE_FUNCTIONAPP_NAME: parkering-api-1759689187
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'parkering-api'
  NODE_VERSION: '20.x'
  SQL_CONNECTION_STRING: ${{ secrets.SQL_CONNECTION_STRING }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build
        popd

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: deploy-to-function
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
# Update deploy.yml for Azure Functions
